# set $PATH
typeset -U path
path=(
	/home/chaisen/.local/bin
	/home/chaisen/.cargo/bin
	/home/chaisen/.go/bin
	/home/chaisen/TeXLive/2017/bin/x86_64-linux
	$path
)

# set $MANPATH
typeset -U path
manpath=(
	/home/chaisen/.local/share/man
	/home/chaisen/TeXLive/2017/texmf-dist/doc/man
	$manpath
)

# set path for neovim bundels
VIMBUNDLE=~/.local/share/nvim/bundle; export VIMBUNDLE
# set path for neovim configs
VIMCONFIG=~/.config/nvim/config; export VIMCONFIG

# set $GOPATH
GOPATH=~/.go; export GOPATH;
