# set $PATH
typeset -U path
path=(
    /home/chaisen/.cargo/bin
    /home/chaisen/.gem/ruby/2.4.0/bin
    /home/chaisen/.go/bin
    /home/chaisen/.cabal/bin
    /home/chaisen/TeXLive/2017/bin/x86_64-linux
    /home/chaisen/node_modules/.bin
    /home/chaisen/.local/bin
    $path
)

# set $MANPATH
typeset -U path
manpath=(
    /home/chaisen/TeXLive/2017/texmf-dist/doc/man
    $manpath
)

# set path for neovim bundels
VIMBUNDLE=~/.local/share/nvim/bundle; export VIMBUNDLE;
# set path for neovim configs
VIMCONFIG=~/.config/nvim/config; export VIMCONFIG;

# set $GOPATH
GOPATH=~/.go; export GOPATH;
