# Set custom prompt, with git support

NT_PROMPT_SYMBOL=' ❱ '

function precmd() {
	autoload -Uz vcs_info
	autoload -U add-zsh-hook
	setopt prompt_subst

	zstyle ':vcs_info*' enable git
	zstyle ':vcs_info:*' check-for-changes true
	zstyle ':vcs_info:*' stagedstr '%F{yellow}⚙%f'
	zstyle ':vcs_info:*' unstagedstr '%F{red}✖%f'
	zstyle ':vcs_info:*' formats ' %F{magenta}[ %b]%f %u%c'

	vcs_info

	if [[ -n $vcs_info_msg_0_ ]]; then
		if [[ -n $(git status --porcelain --ignore-submodules) ]]; then
			git_prompt="$vcs_info_msg_0_"
		else
			git_prompt="$vcs_info_msg_0_%F{green}✔%f"
		fi
	fi

	PROMPT='%F{blue}%1~%f${git_prompt}%(?.%F{green}${NT_PROMPT_SYMBOL}%f.%F{red}${NT_PROMPT_SYMBOL}%f)'
	RPROMPT='%(?.%F{green}$?%f.%F{red}$?%f)'
}


# Source the Environment

# fzf settings
# autocompletion
[[ $- == *i* ]] &&
source ~/.go/src/github.com/junegunn/fzf/shell/completion.zsh 2> /dev/null
# key-bindings
[[ -s ~/.go/src/github.com/junegunn/fzf/shell/key-bindings.zsh ]] &&
source ~/.go/src/github.com/junegunn/fzf/shell/key-bindings.zsh
# use rg instead of find
[[ -x $(which rg) ]] &&
FZF_DEFAULT_COMMAND='rg --files --no-ignore --follow -g ""'; export FZF_DEFAULT_COMMAND;

# stack autocompletion
[[ -x $(which stack) ]] &&
eval "$(stack --bash-completion-script stack)"

# zsh autosuggestions
[[ -s $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ]] &&
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh syntax highlighting
[[ -s $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh ]] &&
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases

# go quick to private wiki
alias wiki='/usr/bin/firefox -P chaisen http://pc.protaisn:5001/'

# a test http server on localhost
alias httpd='/usr/bin/gatling -F -T 23 -P 2M -d -V -i 127.0.0.1 -p 8080'

# use always underscores instead of spaces with youtube-dl
alias youtube-dl='youtube-dl --restrict-filenames'

# don't store su in history
alias su=' su'

# aliases for translation with leo
alias dict='surfraw leodict'

# clone projects from GitHub
GitHub() {
	command git clone 'https://github.com/'"$@"
}

# mosh connections to my uberspace webspaces
alias uber-gsax='mosh -p 62828 uber-gsax'
alias uber-protaisn='mosh -p 61106 uber-protaisn'
alias uber-straemme='mosh -p 63105 uber-straemme'

# ls aliases
alias la='ls -a'
alias ll='ls -lg'
alias llx='ll -@'
alias lla='ll -a'
alias llax='llx -@'
alias llb='ll -b'
alias llbx='lb -@'
alias llba='lb -a'
alias llbax='lba -@'
alias llB='ll -B'
alias llBx='lB -@'
alias llBa='lB -a'
alias llBax='lBa -@'
alias lt='ls -T'
alias ltx='lt -@'
alias lta='lt -a'
alias ltax='lta -@'

# find shortcuts
# case insensitive search
Ff() {
	command bfs . -iname "*$@*"
}
# count all files in a folder
Fc() {
	command bfs "$@" -type f | wc -l
}
# find broken symlinks
Fl() {
	command bfs -L "$@" -type l
}


##########
# PYTHON #
##########

# install required packages
alias PipInstall='pip install khal khard pylama vdirsyncer --user'

# show outdated packages
alias PipListOutdated='pip list --outdated --format=freeze --user | xargs -n1'

# update all manually installed packages
alias PipUpdate='pip list --outdated --format=freeze --user | cut -d = -f 1 | xargs -n1 pip install -U --user'


########
# RUST #
########

# install required packages
alias CargoInstall='
	cargo install tokei &&
	cargo install exa &&
	RUSTFLAGS="-C target-cpu=native" cargo install --features "simd-accel avx-accel" ripgrep &&
	cargo install tealdeer &&
	cargo install racer'

# show all packages installed in the users home
alias CargoList='cargo install --list'

# update all manually installed packages
alias CargoUpdate='
	cargo install --force tokei &&
	cargo install --force exa &&
	RUSTFLAGS="-C target-cpu=native" cargo install --features "simd-accel avx-accel" --force ripgrep &&
	cargo install --force tealdeer &&
	cargo install --force racer'


######
# GO #
######

# install required packages
alias GoInstall='
	go get github.com/zserge/zs \
	github.com/junegunn/fzf \
	github.com/oem/lnch \
	github.com/FooSoft/homemaker \
	github.com/opennota/findimagedupes'

# show all packages installed in the users home
alias GoList='cd ~/.go/ && go list ./... && cd -'

# update all manually installed packages
alias GoUpdate='
	go get -u github.com/zserge/zs \
	github.com/junegunn/fzf \
	github.com/oem/lnch \
	github.com/FooSoft/homemaker \
	github.com/opennota/findimagedupes'
